name: rich_codex

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rich_codex:
    strategy:
      matrix:
        python-version: ["3.10.5"]
        poetry-version: ["1.8.3"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install package
        run: poetry install

      - name: Check Git status
        run: git status

      - name: Make a copy of the argument parser without imports
        run: |
          grep -v "def call_" -A 6 sat/sat.py > .github/tmp/sat_codex.py
          chmod +x .github/tmp/sat_codex.py

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1.2.8
        with:
          commit_changes: "true"
          skip_git_checks: "true"

      - name: Check Git log
        run: git log -3
